version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mektaba_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mektaba
      POSTGRES_PASSWORD: mektaba123
      POSTGRES_DB: mektaba_stock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mektaba_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mektaba.ma
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: